#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xcb-util-image
Version  : 0.4.0
Release  : 2
URL      : https://xcb.freedesktop.org/dist/xcb-util-image-0.4.0.tar.bz2
Source0  : https://xcb.freedesktop.org/dist/xcb-util-image-0.4.0.tar.bz2
Summary  : XCB image convenience library
Group    : Development/Tools
License  : MIT
Requires: xcb-util-image-lib
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : pkgconfig(xcb-shm)
BuildRequires : pkgconfig(xcb-util)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
About XCB util modules
======================
The XCB util modules provides a number of libraries which sit on top
of libxcb, the core X protocol library, and some of the extension
libraries. These experimental libraries provide convenience functions
and interfaces which make the raw X protocol more usable. Some of the
libraries also provide client-side code which is not strictly part of
the X protocol but which have traditionally been provided by Xlib.

%package dev
Summary: dev components for the xcb-util-image package.
Group: Development
Requires: xcb-util-image-lib
Provides: xcb-util-image-devel

%description dev
dev components for the xcb-util-image package.


%package lib
Summary: lib components for the xcb-util-image package.
Group: Libraries

%description lib
lib components for the xcb-util-image package.


%prep
%setup -q -n xcb-util-image-0.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1526052176
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1526052176
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xcb/xcb_bitops.h
/usr/include/xcb/xcb_image.h
/usr/include/xcb/xcb_pixel.h
/usr/lib64/libxcb-image.so
/usr/lib64/pkgconfig/xcb-image.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxcb-image.so.0
/usr/lib64/libxcb-image.so.0.0.0
